/* Arabic shaping and bidirectional ordering, for the PDF only.
 *
 * WHY THIS FILE EXISTS
 *
 * The browser does all of this for us on screen: give it Arabic in logical
 * order and it joins the letters and lays them out right-to-left. A PDF has no
 * such engine. jsPDF writes glyphs left to right at the positions it is given,
 * looks each character up in the font's `cmap`, and does nothing else — no
 * OpenType GSUB, no bidirectional algorithm. Hand it Arabic and you get
 * disconnected letters in backwards order.
 *
 * jsPDF ships its own Arabic parser and it is worse than nothing: it SILENTLY
 * DROPS LETTERS. Proven 2026-08-14 — "بيانات الوحدة" came out "ﺑﻴﺎﻧﺎ ﻟﻮﺣﺪ",
 * short a ت, a ل and a ة, with no error anywhere. That is the failure mode that
 * matters here, because it produces a document that looks plausible to someone
 * who does not read Arabic and is wrong in front of the customer.
 *
 * ITS PARSER NEEDS NO DISABLING, which is the thing that made this look like a
 * much bigger job than it was. jsPDF only touches the BASE Arabic block,
 * U+0600-U+06FF. Text already shaped into Presentation Forms-B, U+FE70-U+FEFF,
 * passes through it completely untouched — so nothing in vendor/ is patched.
 * Shape into the presentation forms, order the run, hand it over. Verified by
 * extracting a finished PDF and comparing codepoint for codepoint against what
 * forPdf() produced.
 *
 * HOW IT WORKS, IN TWO STEPS
 *
 * 1. SHAPE. Arabic letters change form by position — ب is ﺑ at the start of a
 *    word, ﺒ in the middle, ﺐ at the end, ﺏ alone. Unicode has a codepoint for
 *    every one of those forms in the Arabic Presentation Forms-B block
 *    (U+FE70–U+FEFF), which is a deprecated compatibility block that exists for
 *    exactly this situation: a renderer that cannot shape. We pick the right
 *    form per letter from its neighbours and emit those codepoints.
 *
 *    THIS IS WHY THE FONT MATTERS. Most modern Arabic fonts do NOT map the
 *    presentation forms in their cmap — they carry one glyph per letter and
 *    join it with OpenType rules, which jsPDF will not run. Measured coverage
 *    of the 144 Presentation Forms-B codepoints: Amiri 140, Noto Naskh Arabic
 *    141, Cairo 89, Noto Kufi 10. Cairo and Kufi would silently drop glyphs, so
 *    the choice is real but narrow. Amiri is used because it also carries full
 *    ASCII, so a mixed "الدور Sky Plaza" needs one font rather than two.
 *
 * 2. ORDER. Arabic runs right-to-left but numbers and Latin inside it run
 *    left-to-right, so the string has to be reordered into the order the glyphs
 *    are physically drawn. This is a deliberately small subset of the Unicode
 *    Bidirectional Algorithm — enough for "خصم 20% — السعر 1,404,000 ج.م" and
 *    not one line more. It assumes the paragraph is Arabic, which is true of
 *    every string that reaches it.
 *
 * ORDER OF OPERATIONS IS NOT NEGOTIABLE: shape first, reorder second. Shaping
 * reads each letter's neighbours, and after reordering the neighbours are wrong.
 *
 * Everything here is pure string in, string out, so scripts/test-arabic.js can
 * assert on it without a browser or a PDF.
 */

/* ------------------------------------------------------------------ shaping */

/* The Presentation Forms-B block is laid out as one run: every joining letter
 * in codepoint order, each contributing its forms in the order
 * [isolated, final, initial, medial] — two entries for a letter that only ever
 * takes two forms, four for one that takes four. So the table is GENERATED by
 * walking that run rather than typed out as 130-odd hex literals, which is the
 * version that has a transposed digit in it somewhere nobody ever finds.
 *
 * `spec` is the walk: base codepoint, joining class, number of forms.
 *   D = dual-joining     — joins on both sides, has all four forms
 *   R = right-joining    — accepts a join from the right only, so isolated and
 *                          final only, and the NEXT letter cannot join back to
 *                          it (this is why "ادارة" breaks after the ا)
 *   U = non-joining      — ء, which joins nothing and is always isolated
 *
 * U+0640 TATWEEL is deliberately absent from the run: it is dual-joining but
 * has no presentation forms, being already a bare connecting stroke. It is
 * handled as a special case below. Its absence is also the reason the run stays
 * contiguous — U+063A ends at U+FED0 and U+0641 begins at U+FED1.
 */
const AR_SPEC = [
  [0x0621, 'U', 1],                                   // ء
  [0x0622, 'R', 2], [0x0623, 'R', 2], [0x0624, 'R', 2], [0x0625, 'R', 2],
  [0x0626, 'D', 4], [0x0627, 'R', 2], [0x0628, 'D', 4], [0x0629, 'R', 2],
  [0x062A, 'D', 4], [0x062B, 'D', 4], [0x062C, 'D', 4], [0x062D, 'D', 4],
  [0x062E, 'D', 4], [0x062F, 'R', 2], [0x0630, 'R', 2], [0x0631, 'R', 2],
  [0x0632, 'R', 2], [0x0633, 'D', 4], [0x0634, 'D', 4], [0x0635, 'D', 4],
  [0x0636, 'D', 4], [0x0637, 'D', 4], [0x0638, 'D', 4], [0x0639, 'D', 4],
  [0x063A, 'D', 4],
  [0x0641, 'D', 4], [0x0642, 'D', 4], [0x0643, 'D', 4], [0x0644, 'D', 4],
  [0x0645, 'D', 4], [0x0646, 'D', 4], [0x0647, 'D', 4], [0x0648, 'R', 2],
  [0x0649, 'R', 2], [0x064A, 'D', 4],
];

const TATWEEL = 0x0640;

/** base codepoint -> [isolated, final, initial, medial]; the last two null for R. */
const FORMS = new Map();
/** base codepoint -> 'D' | 'R' | 'U'. */
const JOINING = new Map();
(() => {
  let cp = 0xFE80;
  for (const [base, join, n] of AR_SPEC) {
    const iso = cp, fin = n > 1 ? cp + 1 : null;
    const ini = n > 2 ? cp + 2 : null, med = n > 3 ? cp + 3 : null;
    FORMS.set(base, [iso, fin, ini, med]);
    JOINING.set(base, join);
    cp += n;
  }
  JOINING.set(TATWEEL, 'D');
})();

/* LAM + ALEF is not merely a ligature the typographer may take or leave: the
 * pair has no legal uncombined rendering in Arabic, so "لا" MUST become one
 * glyph. Unicode gives the four combinations two forms each. */
const LAM = 0x0644;
const LAM_ALEF = new Map([
  [0x0622, [0xFEF5, 0xFEF6]],   // لآ
  [0x0623, [0xFEF7, 0xFEF8]],   // لأ
  [0x0625, [0xFEF9, 0xFEFA]],   // لإ
  [0x0627, [0xFEFB, 0xFEFC]],   // لا
]);

/* Combining marks — harakat, the shadda, the dagger alef. They hang off the
 * letter before them and are INVISIBLE to joining: "موقّع" joins exactly as
 * "موقع" does, and a shaper that lets the shadda break the join produces
 * disconnected letters that a reader notices immediately. */
function isTransparent(cp) {
  return (cp >= 0x0610 && cp <= 0x061A)
      || (cp >= 0x064B && cp <= 0x065F)
      || cp === 0x0670
      || (cp >= 0x06D6 && cp <= 0x06DC)
      || (cp >= 0x06DF && cp <= 0x06E4)
      || cp === 0x06E7 || cp === 0x06E8
      || (cp >= 0x06EA && cp <= 0x06ED);
}

const isArabicLetter = (cp) => JOINING.has(cp);

/** Does a letter reach forward, so that the NEXT letter takes a joined form? */
const joinsForward = (cp) => JOINING.get(cp) === 'D';
/** Does a letter accept a join from behind, so it can take a final/medial form? */
const joinsBackward = (cp) => JOINING.get(cp) === 'D' || JOINING.get(cp) === 'R';

/**
 * Arabic in logical order -> the same text as presentation forms.
 *
 * Non-Arabic passes through untouched, so a mixed string can be handed straight
 * in. Returns logical order still — reordering is `visual()`, and it has to run
 * second.
 */
function shapeArabic(text) {
  const cps = Array.from(text, (c) => c.codePointAt(0));
  const out = [];

  /* Neighbours SKIPPING marks, which is the whole point of isTransparent. */
  const prevLetter = (i) => {
    for (let j = i - 1; j >= 0; j--) {
      if (isTransparent(cps[j])) continue;
      return isArabicLetter(cps[j]) ? cps[j] : null;
    }
    return null;
  };
  const nextLetter = (i) => {
    for (let j = i + 1; j < cps.length; j++) {
      if (isTransparent(cps[j])) continue;
      return isArabicLetter(cps[j]) ? cps[j] : null;
    }
    return null;
  };

  for (let i = 0; i < cps.length; i++) {
    const cp = cps[i];

    if (!isArabicLetter(cp)) { out.push(cp); continue; }
    if (cp === TATWEEL) { out.push(cp); continue; }

    /* LAM + ALEF, taken as a pair before either is shaped on its own. The
       ligature is final when something joins into the LAM, isolated otherwise —
       the ALEF's own forward join is irrelevant because ALEF never joins
       forward. */
    if (cp === LAM) {
      const nxt = nextLetter(i);
      if (nxt !== null && LAM_ALEF.has(nxt)) {
        const before = prevLetter(i);
        const joined = before !== null && joinsForward(before);
        out.push(LAM_ALEF.get(nxt)[joined ? 1 : 0]);
        /* Consume through the alef, keeping any marks that sat between them. */
        for (let j = i + 1; j < cps.length; j++) {
          if (cps[j] === nxt) { i = j; break; }
          out.push(cps[j]);
        }
        continue;
      }
    }

    const before = prevLetter(i), after = nextLetter(i);
    const linkedBack = before !== null && joinsForward(before) && joinsBackward(cp);
    const linkedFwd  = after !== null && joinsBackward(after) && joinsForward(cp);

    const [iso, fin, ini, med] = FORMS.get(cp);
    let form = iso;
    if (linkedBack && linkedFwd) form = med || fin || iso;
    else if (linkedBack) form = fin || iso;
    else if (linkedFwd) form = ini || iso;
    out.push(form);
  }

  return String.fromCodePoint(...out);
}

/* ------------------------------------------------------------------- order  */

/* Bidi classes, cut to the ones this document can actually contain. */
const CLS = { R: 'R', L: 'L', EN: 'EN', ET: 'ET', CS: 'CS', N: 'N' };

function classOf(ch) {
  const cp = ch.codePointAt(0);
  if ((cp >= 0x0600 && cp <= 0x06FF) || (cp >= 0xFB50 && cp <= 0xFDFF)
      || (cp >= 0xFE70 && cp <= 0xFEFF)) return CLS.R;
  if (ch >= '0' && ch <= '9') return CLS.EN;
  if (/[A-Za-zÀ-ɏ]/.test(ch)) return CLS.L;
  /* Superscripts and the degree sign attach to a LETTER, not to a number — the
     one that matters here is the ² in "39.78 m²". Classing them as terminators
     put the ² on the far side of the line from its m, because the terminator
     rule below only looks for an adjacent digit. They are Latin. */
  if (ch === '²' || ch === '³' || ch === '°') return CLS.L;
  /* European terminators: they belong to the number beside them, which is why
     "20%" survives as one atom instead of the % drifting off to the far side of
     the line. Currency signs are here for the same reason. */
  if (ch === '%' || ch === '$' || ch === '£' || ch === '€'
      || ch === '+' || ch === '-' || ch === '−') return CLS.ET;
  /* Common separators, which join two numbers into one: 1,404,000 and 39.78. */
  if (ch === ',' || ch === '.' || ch === ':' || ch === '/' || ch === ' ') return CLS.CS;
  return CLS.N;
}

/* Mirrored pairs. At an RTL level an opening bracket is drawn as a closing one,
 * because "الصيانة (9%)" must still open on the right. */
const MIRROR = new Map(Object.entries({
  '(': ')', ')': '(', '[': ']', ']': '[', '{': '}', '}': '{',
  '<': '>', '>': '<', '«': '»', '»': '«', '‹': '›', '›': '‹',
}));

/* Invisible formatting characters. bidiSafe() in i18n.js wraps screen values in
 * isolates, and if one of those strings ever reaches the PDF the isolate has no
 * glyph and jsPDF draws .notdef — a black box in the middle of a price. They
 * carry no information we need here, because this file works the direction out
 * from the characters themselves, so they are dropped on the way in. */
const FORMAT_CHARS = /[‎‏‪-‮⁦-⁩؜]/g;

/**
 * Logical order -> the order the glyphs are physically drawn, left to right.
 *
 * A cut-down Unicode Bidirectional Algorithm with the paragraph direction fixed
 * to RTL. Two levels are enough for this document: 1 for Arabic, 2 for a run of
 * Latin or digits embedded in it.
 */
function visualOrder(text) {
  const chars = Array.from(text.replace(FORMAT_CHARS, ''));
  if (!chars.length) return '';
  const cls = chars.map(classOf);

  /* A separator between two numbers is part of the number. Done before
     anything else so 1,404,000 is one atom rather than three. */
  for (let i = 0; i < cls.length; i++) {
    if (cls[i] !== CLS.CS) continue;
    if (cls[i - 1] === CLS.EN && cls[i + 1] === CLS.EN) cls[i] = CLS.EN;
  }
  /* A terminator touching a number is part of the number. */
  for (let i = 0; i < cls.length; i++) {
    if (cls[i] !== CLS.ET) continue;
    if (cls[i - 1] === CLS.EN || cls[i + 1] === CLS.EN) cls[i] = CLS.EN;
  }

  /* Levels: Arabic and anything unresolved sit at the paragraph level. */
  const level = cls.map((c) => (c === CLS.L || c === CLS.EN) ? 2 : 1);

  /* Neutrals — spaces, dashes, bullets — take the embedded level only when
     BOTH sides are Latin-ish. That is what keeps "15 Aug 2026" and "39.78 m²"
     whole while leaving the spaces around an Arabic word to the Arabic.

     BRACKETS ARE EXEMPT, and are pinned to the paragraph level. A bracket is
     half of a pair, and the two halves have to end up at the SAME level or the
     mirroring below flips one and not the other — "الوقت 1 (1)" came out with
     two opening brackets and no closing one, because the opening bracket had a
     number on each side and got absorbed into the Latin run while its partner,
     with nothing to its right, did not. The full algorithm resolves this by
     matching pairs (rule N0); pinning them is the same answer for a document
     whose brackets never nest, and it is one line rather than fifty. */
  const promotable = (k) => cls[k] !== CLS.R && !MIRROR.has(chars[k]);
  let i = 0;
  while (i < chars.length) {
    if (level[i] === 2 || !promotable(i)) { i++; continue; }
    let j = i;
    while (j < chars.length && level[j] === 1 && promotable(j)) j++;
    const leftOk = i > 0 && level[i - 1] === 2;
    const rightOk = j < chars.length && level[j] === 2;
    if (leftOk && rightOk) for (let k = i; k < j; k++) level[k] = 2;
    i = j;
  }

  /* Rule L2, with only two levels to walk: reverse each embedded run, then
     reverse the line. The embedded runs come out in their original internal
     order but positioned right to left, which is exactly the intent. */
  const outChars = chars.slice();
  i = 0;
  while (i < outChars.length) {
    if (level[i] < 2) { i++; continue; }
    let j = i;
    while (j < outChars.length && level[j] >= 2) j++;
    const run = outChars.slice(i, j).reverse();
    for (let k = i; k < j; k++) outChars[k] = run[k - i];
    i = j;
  }
  /* Mirror what is still at an RTL level, before the line flips. */
  for (let k = 0; k < outChars.length; k++) {
    if (level[k] === 1 && MIRROR.has(outChars[k])) outChars[k] = MIRROR.get(outChars[k]);
  }
  outChars.reverse();

  return outChars.join('');
}

/** True if the string contains anything that needs shaping at all. */
function hasArabic(text) {
  return /[؀-ۿﭐ-﷿ﹰ-﻿]/.test(String(text == null ? '' : text));
}

/**
 * The one call the PDF makes: logical Arabic in, drawable glyph order out.
 *
 * Non-Arabic strings come back untouched — not merely unchanged in appearance,
 * but the same string — so every label in the document can go through this
 * without the English pages caring.
 */
function forPdf(text) {
  const s = String(text == null ? '' : text);
  if (!hasArabic(s)) return s;
  return visualOrder(shapeArabic(s));
}

/* --------------------------------------------------------------- for tests  */

/** Presentation form -> the base letter it came from. Inverse of shaping. */
const UNSHAPE = new Map();
for (const [base, forms] of FORMS) {
  for (const f of forms) if (f !== null) UNSHAPE.set(f, base);
}
for (const [alef, forms] of LAM_ALEF) {
  for (const f of forms) UNSHAPE.set(f, [LAM, alef]);
}

/**
 * Undo shaping — every presentation form back to the letter it came from.
 *
 * Built from the INVERSE of the generated tables rather than from the same
 * logic, so `unshape(shapeArabic(s)) === s` is a real assertion about the
 * shaper and not a restatement of it. That equality is what proves no letter
 * was dropped, which is the exact bug jsPDF's own parser had. Not used at run
 * time.
 *
 * There is deliberately NO inverse of visualOrder(). Reordering is a
 * permutation whose levels were resolved from the LOGICAL neighbours, and those
 * neighbours are gone once the string is reordered — a trailing full stop that
 * ended up beside a number is indistinguishable from one that was always there.
 * An "inverse" would have to guess, and a test whose oracle guesses is worse
 * than no test. Ordering is asserted two other ways instead: exact expected
 * output on hand-checked strings, and a multiset check that nothing is lost.
 */
function unshape(text) {
  const out = [];
  for (const ch of Array.from(text)) {
    const base = UNSHAPE.get(ch.codePointAt(0));
    if (base === undefined) out.push(ch);
    else if (Array.isArray(base)) out.push(String.fromCodePoint(base[0]), String.fromCodePoint(base[1]));
    else out.push(String.fromCodePoint(base));
  }
  return out.join('');
}

if (typeof window !== 'undefined') {
  window.forPdf = forPdf; window.hasArabic = hasArabic;
}
if (typeof module !== 'undefined') {
  module.exports = { forPdf, unshape, shapeArabic, visualOrder, hasArabic, FORMS, JOINING };
}
