/* Build vendor/fonts.js — the brand typefaces, base64'd for jsPDF's VFS.
 *
 *   node scripts/make-fonts.js
 *
 * WHY THIS EXISTS
 *
 * jsPDF's built-in fonts are the PDF "standard 14": the file merely NAMES
 * Helvetica and trusts the reader to own a copy. Acrobat and Chrome substitute
 * silently, so it looks fine on a laptop — but WhatsApp's in-app viewer on
 * Android and a lot of stock phone viewers have no Helvetica, and the client
 * reported text simply not showing. An offer that renders blank on the device
 * it is actually read on is not an offer. So the fonts are embedded.
 *
 * THE FONTS
 *
 * Chosen against the client's own wordmark (assets/logo-full.png): "Qomor" is
 * a light high-contrast serif over "BUSINESS PLAZA" in tracked-out sans caps.
 *
 *   Marcellus            display — page and section titles, the cover
 *   Montserrat Regular   body, labels, tables
 *   Montserrat SemiBold  prices, headings, anything that carries weight
 *
 * Both are SIL Open Font License 1.1, which permits embedding in a document.
 * The licences ship beside the fonts in assets/fonts/ — keep them there.
 *
 * PROVENANCE — assets/fonts/*.ttf are SUBSETS, not the originals:
 *
 *   Montserrat  https://github.com/JulietaUla/Montserrat  fonts/ttf/
 *   Marcellus   https://github.com/google/fonts           ofl/marcellus/
 *
 * cut to Latin-1 plus the typographic marks latin() permits, with
 * `subset-font` (npm, one-off — deliberately NOT a dependency of this app).
 * Montserrat ships Cyrillic and Vietnamese that can never reach the page:
 * 435 KB -> 94 KB per weight. To regenerate from the originals:
 *
 *   npm i subset-font
 *   node -e "..."   # keep U+0020-007E, U+00A0-00FF, dashes/quotes/bullet/minus
 *
 * SIZE
 *
 * ~218 KB of TTF becomes ~290 KB of base64. That is why vendor/fonts.js is
 * loaded lazily alongside jsPDF and never on first paint — see pdf.js. jsPDF
 * subsets again on the way into the PDF, so an offer only carries the glyphs
 * it actually prints (~60 KB of the 218 KB).
 */
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');

/* [file, jsPDF family, jsPDF style] — the style strings pdf.js asks for. */
const FONTS = [
  ['Marcellus-Regular.ttf',   'Marcellus',  'normal'],
  ['Montserrat-Regular.ttf',  'Montserrat', 'normal'],
  ['Montserrat-SemiBold.ttf', 'Montserrat', 'bold'],
];

const parts = FONTS.map(([file, family, style]) => {
  const b64 = fs.readFileSync(path.join(root, 'assets/fonts', file)).toString('base64');
  return `  ['${file}', '${family}', '${style}',\n   '${b64}'],`;
});

const out = `/* GENERATED by scripts/make-fonts.js — do not edit by hand.
 *
 * The Qomor brand typefaces as base64 TrueType, for jsPDF's virtual file
 * system. Marcellus and Montserrat, both SIL OFL 1.1; licences in
 * assets/fonts/. Regenerate with: node scripts/make-fonts.js
 *
 * Registration is per DOCUMENT, not on jsPDF.API: the API object has no
 * \`internal\`, and addFileToVFS reads this.internal.vFS, so calling it on the
 * prototype throws. QOMOR_FONTS is consumed by registerFonts() in js/pdf.js.
 */
var QOMOR_FONTS = [
${parts.join('\n')}
];

if (typeof window !== 'undefined') window.QOMOR_FONTS = QOMOR_FONTS;
if (typeof module !== 'undefined') module.exports = QOMOR_FONTS;
`;

const dest = path.join(root, 'vendor/fonts.js');
fs.writeFileSync(dest, out);
console.log(`wrote ${path.relative(root, dest)}  (${(out.length / 1024).toFixed(0)} KB)`);
for (const [file] of FONTS) {
  console.log(`  ${file.padEnd(26)} ${(fs.statSync(path.join(root, 'assets/fonts', file)).size / 1024).toFixed(0)} KB`);
}
