/* Build vendor/fonts.js — the brand typefaces, base64'd for jsPDF's VFS.
 *
 *   node scripts/make-fonts.js
 *
 * WHY THIS EXISTS
 *
 * jsPDF's built-in fonts are the PDF "standard 14": the file merely NAMES
 * Helvetica and trusts the reader to own a copy. Acrobat and Chrome substitute
 * silently, so it looks fine on a laptop — but WhatsApp's in-app viewer on
 * Android and a lot of stock phone viewers have no Helvetica, and the client
 * reported text simply not showing. An offer that renders blank on the device
 * it is actually read on is not an offer. So the fonts are embedded.
 *
 * THE FONTS
 *
 * Chosen against the client's own wordmark (assets/logo-full.png): "Qomor" is
 * a light high-contrast serif over "BUSINESS PLAZA" in tracked-out sans caps.
 *
 *   Marcellus            display — page and section titles, the cover
 *   Montserrat Regular   body, labels, tables
 *   Montserrat SemiBold  prices, headings, anything that carries weight
 *   Amiri Regular/Bold   ALL Arabic, and the Latin sitting inside it
 *
 * All SIL Open Font License 1.1, which permits embedding in a document. The
 * licences ship beside the fonts in assets/fonts/ — keep them there.
 *
 * PROVENANCE — assets/fonts/*.ttf are SUBSETS, not the originals:
 *
 *   Montserrat  https://github.com/JulietaUla/Montserrat  fonts/ttf/
 *   Marcellus   https://github.com/google/fonts           ofl/marcellus/
 *   Amiri       https://github.com/google/fonts           ofl/amiri/
 *
 * cut with `subset-font` (npm, one-off — deliberately NOT a dependency of this
 * app). The Latin faces keep Latin-1 plus the typographic marks latin()
 * permits; Montserrat ships Cyrillic and Vietnamese that can never reach the
 * page, 435 KB -> 94 KB per weight. Amiri keeps ASCII, Latin-1, the Arabic
 * COMBINING MARKS and Arabic Presentation Forms-B — but NOT the bare Arabic
 * letters, which can never be asked for because js/arabic.js emits every letter
 * as a presentation form: 421 KB -> 138 KB. To regenerate from the originals:
 *
 *   npm i subset-font
 *   node -e "..."   # keep U+0020-007E, U+00A0-00FF, dashes/quotes/bullet/minus
 *
 * SIZE
 *
 * ~218 KB of TTF becomes ~290 KB of base64. That is why vendor/fonts.js is
 * loaded lazily alongside jsPDF and never on first paint — see pdf.js. jsPDF
 * subsets again on the way into the PDF, so an offer only carries the glyphs
 * it actually prints (~60 KB of the 218 KB).
 */
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');

/* TWO BUNDLES, and the split is the point.
 *
 * Arabic needs a face the Latin ones do not have a single glyph of, and Amiri
 * subsets to ~282 KB — as much again as the whole Latin set. Putting it in
 * vendor/fonts.js would make every ENGLISH export pay 376 KB of base64 for
 * glyphs it can never draw. So the Arabic bundle is a separate file that
 * pdf.js fetches only when the offer is actually being written in Arabic.
 *
 * [file, jsPDF family, jsPDF style] — the style strings pdf.js asks for. */
const LATIN = [
  ['Marcellus-Regular.ttf',   'Marcellus',  'normal'],
  ['Montserrat-Regular.ttf',  'Montserrat', 'normal'],
  ['Montserrat-SemiBold.ttf', 'Montserrat', 'bold'],
];

/* Amiri is the Arabic face, and the choice was forced rather than aesthetic.
 * jsPDF runs no OpenType shaping, so js/arabic.js shapes into the Arabic
 * Presentation Forms-B block and the font must map those codepoints in its
 * cmap. Measured coverage of the 144: Amiri 140, Noto Naskh Arabic 141,
 * Cairo 89, Noto Kufi 10 — the last two would silently drop glyphs, which is
 * the exact failure this whole exercise exists to remove. Amiri also carries
 * full ASCII, so a mixed "الدور Sky Plaza" needs one font and not two. */
const ARABIC = [
  ['Amiri-Regular.ttf', 'Amiri', 'normal'],
  ['Amiri-Bold.ttf',    'Amiri', 'bold'],
];

function bundle(fonts, globalName, dest, blurb) {
  const parts = fonts.map(([file, family, style]) => {
    const b64 = fs.readFileSync(path.join(root, 'assets/fonts', file)).toString('base64');
    return `  ['${file}', '${family}', '${style}',\n   '${b64}'],`;
  });

  const out = `/* GENERATED by scripts/make-fonts.js — do not edit by hand.
 *
 * ${blurb}
 * Regenerate with: node scripts/make-fonts.js
 *
 * Registration is per DOCUMENT, not on jsPDF.API: the API object has no
 * \`internal\`, and addFileToVFS reads this.internal.vFS, so calling it on the
 * prototype throws. Consumed by registerFonts() in js/pdf.js.
 */
var ${globalName} = [
${parts.join('\n')}
];

if (typeof window !== 'undefined') window.${globalName} = ${globalName};
if (typeof module !== 'undefined') module.exports = ${globalName};
`;

  fs.writeFileSync(path.join(root, dest), out);
  console.log(`wrote ${dest}  (${(out.length / 1024).toFixed(0)} KB)`);
  for (const [file] of fonts) {
    console.log(`  ${file.padEnd(26)} ${(fs.statSync(path.join(root, 'assets/fonts', file)).size / 1024).toFixed(0)} KB`);
  }
}

bundle(LATIN, 'QOMOR_FONTS', 'vendor/fonts.js',
       'Marcellus and Montserrat as base64 TrueType, both SIL OFL 1.1.');
bundle(ARABIC, 'QOMOR_FONTS_AR', 'vendor/fonts-ar.js',
       'Amiri as base64 TrueType, SIL OFL 1.1. Loaded only for an Arabic offer.');
